#!/usr/bin/env node
import { execSync } from "node:child_process";
import { readFileSync, writeFileSync, mkdirSync, existsSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");

function gitOrEmpty(cmd) {
  try {
    return execSync(cmd, { cwd: repoRoot, encoding: "utf8", stdio: ["ignore", "pipe", "ignore"] }).trim();
  } catch {
    return "";
  }
}

const pkg = JSON.parse(readFileSync(resolve(repoRoot, "package.json"), "utf8"));
const fallback = `v${pkg.version}`;

const describe = gitOrEmpty("git describe --tags --always --dirty");
const sha = gitOrEmpty("git rev-parse --short=7 HEAD");
const exactTag = gitOrEmpty("git describe --tags --exact-match HEAD");

let version = fallback;
if (exactTag) {
  version = exactTag;
} else if (describe) {
  version = describe.startsWith("v") ? describe : `${fallback}-${sha || describe}`;
}

const out = resolve(repoRoot, "src/version.generated.ts");
const banner = `// AUTO-GENERATED by scripts/gen-version.mjs. DO NOT EDIT.
// Regenerated on every \`npm run dev\`/\`deploy\`.
export const APP_VERSION = ${JSON.stringify(version)};
export const APP_GIT_SHA = ${JSON.stringify(sha)};
`;

mkdirSync(dirname(out), { recursive: true });
const prev = existsSync(out) ? readFileSync(out, "utf8") : "";
if (prev !== banner) writeFileSync(out, banner);
console.log(`[gen-version] APP_VERSION=${version}${sha ? ` (sha=${sha})` : ""}`);
